name: 'chronos'

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "${COMPOSE_INFLUXDB_HOST_PORT:-8086}:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
    env_file:
      - .env

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${COMPOSE_DOCKER_HOST_PORT:-3080}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
