name: 'chronos'

services:
  api:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env.api_server
    networks:
      - influx-db-network

networks:
  influx-db-network:
    external: true
    name: ${DOCKER_COMPOSE_INFLUX_DB_NETWORK}
