version: '3'

# Taskfile のドキュメント: https://taskfile.dev/usage/

tasks:
  default:
    cmds:
      - task: list-tasks

  list-tasks:
    desc: タスクランナー `task` のタスクを一覧表示する。
    cmd: task --list
    silent: true

  #--------------------------------------------
  # lint, format

  fmt:
    desc: C++のソースコードを整形する。
    cmd: find src lib include test -type f \( -name '*.hpp' -o -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 clang-format -i

  lint:
    desc: cppcheckでlintする。
    cmd: pio check --fail-on-defect low --skip-packages

  build:
    desc: ビルドする。
    cmd: pio run
