version: '3'

# Taskfile のドキュメント: https://taskfile.dev/usage/

tasks:
  default:
    cmds:
      - task: list-tasks

  list-tasks:
    desc: タスクランナー `task` のタスクを一覧表示する。
    cmd: task --list
    silent: true

  #--------------------------------------------
  # lint, format, typecheck

  fmt:
    desc: C++のソースコードを整形する。
    cmd: find . -type f \( -name '*.hpp' -o -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 clang-format -i
