name: Test arduino
on:
  pull_request:
    paths:
      - arduino/**
      - .github/workflows/test_arduino.yml
  push:
    paths:
      - arduino/**
      - .github/workflows/test_arduino.yml
    branches:
      - main

jobs:
  build-and-lint:
    name: Build & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: arduino

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio
          path: |
            ~/.cache/pip
            ~/.platformio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Prepare dummy env.h
        run: cp src/env.example.h src/env.h

      - name: Build
        run: pio run

      - name: Lint
        run: pio check --fail-on-defect low --skip-packages

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - src
          - lib
          - include
          - test

    steps:
      - uses: actions/checkout@v4

      - uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '17'
          check-path: ${{ matrix.path }}
